/* eslint-disable no-undef */
describe('Create user page', () => {
  it('should navigate to users and open the modal', () => {
    cy.loginAsAdmin()
    cy.getByDataCy('project_show').should('exist')
    cy.getByDataCy('user_menu').click()
    cy.getByDataCy('menu_users').click()
    cy.getByDataCy('datatable_menu').first().click()
    cy.getByDataCy('datatable_edit').first().click()
    cy.get('header').should('contain', 'Edit user')
    cy.get('input').should('have.length', 5)
    cy.getSelect('role').should('have.length', 1)
    cy.getByForm('text', 'firstName')
      .should('have.value', 'Quentin')
      .clear()
      .type('Alain')
    cy.getByForm('text', 'lastName')
      .should('have.value', 'Fresco')
      .clear()
      .type('Girard')
    cy.getByForm('email', 'email')
      .should('have.value', 'quentin.fresco@wavemind.ch')
      .clear()
      .type('alain.girard@wavemind.ch')
    cy.getSelect('role').select('Deployment Manager').should('have.value', 2)
    cy.getByForm('text', 'projects')
      .should('have.value', 'Project')
      .clear()
      .type('Updated project')
    // cy.getByDataCy('find_projects').first().click()
    // cy.getByDataCy('allowed_projects').should('exist')
    // cy.getByDataCy('toggle_admin_allowed_projects')
    //   .first()
    //   .click({ force: true })
    cy.getByDataCy('submit').click()
    cy.get('h2').should('contain', 'Users')
  })

  // it("should be redirect to '/' because he doesn't have access", () => {
  //   cy.login('/users')
  //   cy.getByDataCy('new_user').should('not.exist')
  //   cy.get('h2').should('contain', 'Projects')
  // })
})
