development:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DEV_DB_NAME'] %>
  pool: 10
  timeout: 4
  username:  <%= ENV['DEV_DB_USERNAME'] %>
  password:  <%= ENV['DEV_DB_PASSWORD'] %>
