source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.4'

gem 'bootsnap', require: false
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.4'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Added
gem 'apollo_upload_server', '2.1'
gem 'devise' # Needed due to rails 7
gem 'devise_invitable', '~> 2.0.0'
gem 'devise_token_auth', github: 'lynndylanhurley/devise_token_auth', branch: 'master'
gem 'devise-two-factor'
gem 'graphql'
gem 'hstore_translate'
gem 'nilify_blanks'
gem 'rack-cors'
gem 'ransack'
gem 'sentry-rails'
gem 'sentry-ruby'

group :development, :test do
  gem 'byebug', '~> 11.1'
  gem 'database_cleaner'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'rspec-rails', '~> 4.0.1'
  gem 'shoulda-matchers'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
  gem 'graphiql-rails'
  gem 'sass-rails'
  gem 'therubyracer'
  gem 'uglifier'
end
