name: 'Deployement in dev'

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # specify the `main` branch as the remote branch to push to
          branch: 'develop'
          git_remote_url: 'ssh://dokku@159.89.107.95:22/api'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
