name: Lint Code Base
on:
  push:
    branches-ignore: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
        with:
          working-directory: front
        run: yarn lint
