name: Lint Code Base
on:
  push:
    branches-ignore: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          working-directory: front
        run: yarn lint
