name: End-to-end tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          working-directory: api
          ruby-version: "3.0.3"

      - name: Install dependencies
        working-directory: api
        run: bundle install

      - name: Create database
        working-directory: api
        run: bundle exec rake db:create

      - name: Start rails server
        working-directory: api
        run: rails s &

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: front
          start: yarn dev
          browser: chrome
          wait-on: 'http://localhost:3001'
          wait-on-timeout: 120
