name: End-to-end tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Start docker containers
        run: |
          echo "VERSION=$(versioninfo)" >> $GITHUB_ENV
          docker-compose up --build --detach
          sleep 10  # wait for database to be ready
          docker-compose run web bash -c "rails db:create && rails db:migrate && rails db:seed"

      - name:  Run backend unit and integration tests
        run: "echo 'Do something'"

      - name: Run cypress e2e tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: front/cypress
          wait-on: "http://localhost:3000"

      - if: always()
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          name: "Run tests"
          status: "${{ job.status }}"


