name: End-to-end tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: front
          start: yarn dev
          browser: chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120